#!/bin/bash
# Pulse Multi-Agent Launch Script
# Run this to see the exact commands for each terminal window

REPO="/Users/aaryapatel/garrysupreme"

echo "=========================================="
echo "  PULSE MULTI-AGENT WORKFLOW LAUNCHER"
echo "=========================================="
echo ""
echo "Open 5 terminal tabs/windows and run one command in each:"
echo ""
echo "--- TAB 1: CEO (Opus 4.7) ---"
echo "cd $REPO && claude --model opus --print-cost"
echo "Then paste: Read roles/CEO.md and workflow/PROTOCOL.md. You are the CEO. Begin immediately — create Phase 1 tasks for Stupid Coder and start orchestrating. Use /loop 60 to poll."
echo ""
echo "--- TAB 2: SMART CODER (Opus 4.7) ---"
echo "cd $REPO && claude --model opus --print-cost"
echo "Then paste: Read roles/SMART_CODER.md and SMART_CODER_PROMPT.md. You are the Smart Coder. Use /loop 45 to watch workflow/inbox-smart/ for tasks."
echo ""
echo "--- TAB 3: STUPID CODER (Sonnet) ---"
echo "cd $REPO && claude --model sonnet --print-cost"
echo "Then paste: Read roles/STUPID_CODER.md and STUPID_CODER_PROMPT.md. You are the Stupid Coder. Use /loop 30 to watch workflow/inbox-stupid/ for tasks."
echo ""
echo "--- TAB 4: DEBUGGER (Opus 4.7) ---"
echo "cd $REPO && claude --model opus --print-cost"
echo "Then paste: Read roles/DEBUGGER.md. You are the Debugger. Use /loop 90 to watch workflow/done/ for completed tasks to review."
echo ""
echo "--- TAB 5: BOARD MEMBER (you manually or another Claude) ---"
echo "cd $REPO && watch -n 10 'ls workflow/board-questions/ 2>/dev/null && echo --- && cat workflow/board-questions/*.md 2>/dev/null'"
echo "Or run another Claude: cd $REPO && claude"
echo "Then paste: Read roles/BOARD_MEMBER.md. You are the Board Member. Watch workflow/board-questions/ and answer promptly."
echo ""
echo "=========================================="
echo "  QUICK START (paste into each Claude):"
echo "=========================================="
echo ""
echo "CEO:          I am the CEO. Read roles/CEO.md, workflow/PROTOCOL.md, and pulse_final_build_plan_with_vapi_v2.0.md. Begin orchestrating now."
echo ""
echo "SMART CODER:  I am the Smart Coder. Read roles/SMART_CODER.md and SMART_CODER_PROMPT.md. Start /loop 45 watching workflow/inbox-smart/"
echo ""
echo "STUPID CODER: I am the Stupid Coder. Read roles/STUPID_CODER.md and STUPID_CODER_PROMPT.md. Start /loop 30 watching workflow/inbox-stupid/"
echo ""
echo "DEBUGGER:     I am the Debugger. Read roles/DEBUGGER.md. Start /loop 90 watching workflow/done/"
echo ""
echo "=========================================="
